### PR TITLE
Zilien datasets with integrated Biologic datasets

### PR DESCRIPTION
**Pull request by matenestor**
The PR contains three datasets, each with Zilien dataset (tsv file) and Biologic datasets (mpt files). The Biologic mpt files are integrated inside the Zilien tsv file, which is now considered version 2. The datasets are used for testing a new version of Ixdat's Zilien reader, that is able to read such integrated Zilien datasets. The three datasets are present in a `zilien_version_2` directory.

The datasets consists of following:
- `test-1` -- data from 1 Zilien measurement with 1 Biologic technique set (used techniques were CV and CP)
- `test-2` -- data from 2 Zilien measurements both with the 1 same Biologic technique set (used techniques were CV and CP)
- `test-3` -- data from 1 Zilien measurement with 2 Biologic technique set (the first Biologic measurement used technique was CV and the second one CP)
 
In an addition, the dataset used during testing of reading the Zilien dataset file format version 1 had been moved in here from the orginal _ixdat_ repository. It is present in a `zilien_version_1` directory.

### CODE REVIEW

**Comment by KennethNielsen** [comment]
A few questions:

> test-2 -- data from 2 Zilien measurements both with the 1 same Biologic technique set (used techniques were CV and CP)

We need to sort our terminology here. I guess by "Zilien measurement" you refer to starting a EC-Lab measurement from Zilien. If so, I understand, but I don't agree with the terminology. I think we need to refer to them as "2 triggered EC-Lab experiment".

Second: You mention only adding data, but the PR has changes to a lot of other files. Is this intentional and if so, what are the changes?

**Comment by matenestor** [comment]
Yes, you are right. The "Zilien experiment" really means "a triggered EC-Lab experiment".

And the changes to other files is just renaming the directories where they live, so it is easier to distinguish which product does a dataset pertain to.

**Review by KennethNielsen — APPROVED** [review]
Size is reasonable, approved on my end.

**Comment by KennethNielsen** [comment]
@ScottSoren do you want a look at PRs like this, or should I just merge?

**Comment by ScottSoren** [comment]
This looks good! Sorry I didn't see it when reviewing ixdat/#100 a couple weeks ago. Merging it now.

**Comment by ScottSoren** [comment]
> @ScottSoren do you want a look at PRs like this, or should I just merge?

Sorry, I didn't see this before vacation. 

No strong feelings - what do you think is the best workflow?
I take it a PR here will usualy be connected to a PR in ixdat/ixdat. I don't think I personally need to be involved if it has to do specifically with e.g. Zilien (you guys are the experts then), but I would say that a PR here should be reviewed alongside the corresponding PR in ixdat/ixdat.

**Pull request merged**
